import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import {
  ComplianceEvidenceItem,
  ComplianceEvidenceRun,
  ComplianceFramework,
} from '@/lib/complianceDatabase';

/**
 * Phase 2 #4c — generate a downloadable audit package for one evidence run.
 *
 * The ZIP contains:
 *   - cover.pdf            — auditor-facing summary (framework, tenant, counts, control table)
 *   - manifest.json        — machine-readable run metadata + control list
 *   - controls/<code>.json — full snapshot per control (the raw evidence)
 *
 * Generation runs entirely in the browser. No round-trip to an edge function
 * needed; the data is already loaded by the time the user clicks Download.
 */

export interface PackageInput {
  run: ComplianceEvidenceRun;
  framework: ComplianceFramework;
  items: ComplianceEvidenceItem[];
  tenantName: string;
  generatedBy?: string;
  /** Optional AI-generated narratives, keyed by item id. */
  narratives?: Record<string, string>;
}

function safeFileName(s: string): string {
  return s.replace(/[^\w.-]+/g, '_').slice(0, 80);
}

function statusLabel(s: string): string {
  return s.toUpperCase();
}

function buildCoverPdf(input: PackageInput): Blob {
  const { run, framework, items, tenantName, generatedBy } = input;
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const margin = 48;
  let y = margin;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('Compliance Evidence Report', margin, y);
  y += 28;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(80);
  doc.text(`${framework.name}${framework.version ? ` · ${framework.version}` : ''}`, margin, y);
  y += 16;
  doc.text(`Tenant: ${tenantName}`, margin, y);
  y += 14;
  doc.text(
    `Evaluated at: ${run.completedAt ? run.completedAt.toLocaleString() : run.startedAt.toLocaleString()}`,
    margin,
    y
  );
  y += 14;
  if (generatedBy) {
    doc.text(`Generated by: ${generatedBy}`, margin, y);
    y += 14;
  }

  // Summary box
  y += 12;
  doc.setDrawColor(200);
  doc.rect(margin, y, 540 - margin * 2 + margin, 70);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20);
  doc.setFontSize(12);
  doc.text('Summary', margin + 12, y + 18);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const summaryLine = `${run.passedCount} pass · ${run.failedCount} fail · ${run.naCount} N/A${
    run.errorCount ? ` · ${run.errorCount} error` : ''
  } (out of ${run.totalControls} controls evaluated)`;
  doc.text(summaryLine, margin + 12, y + 38);
  const overall =
    run.failedCount === 0 && run.errorCount === 0
      ? 'PASS — No failed controls in this run.'
      : `ATTENTION — ${run.failedCount + run.errorCount} control(s) need review.`;
  doc.text(overall, margin + 12, y + 56);
  y += 90;

  // Control table
  autoTable(doc, {
    startY: y,
    head: [['Control', 'Name', 'Severity', 'Status', 'Notes']],
    body: items.map((it) => [
      it.control?.controlCode ?? '',
      it.control?.name ?? '',
      (it.control?.severity ?? '').toUpperCase(),
      statusLabel(it.status),
      it.notes ?? '',
    ]),
    styles: { fontSize: 9, cellPadding: 5, overflow: 'linebreak' },
    headStyles: { fillColor: [40, 40, 40], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 90 },
      2: { cellWidth: 60 },
      3: { cellWidth: 50 },
      4: { cellWidth: 'auto' },
    },
    didParseCell: (data) => {
      if (data.section !== 'body' || data.column.index !== 3) return;
      const status = String(data.cell.raw).toLowerCase();
      if (status === 'pass') data.cell.styles.textColor = [16, 122, 87];
      else if (status === 'fail') data.cell.styles.textColor = [180, 35, 35];
      else if (status === 'error') data.cell.styles.textColor = [200, 130, 0];
      else data.cell.styles.textColor = [120, 120, 120];
    },
  });

  // AI narratives (issue #4) — only render the section when at least one is supplied.
  if (input.narratives && Object.keys(input.narratives).length > 0) {
    doc.addPage();
    let nY = margin;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(20);
    doc.text('AI-generated narratives', margin, nY);
    nY += 22;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      'Plain-language explanations of failed/at-risk controls. Generated by AI; verify before relying on for audit response.',
      margin,
      nY,
      { maxWidth: 540 - margin }
    );
    nY += 24;

    const itemsById = new Map(items.map((it) => [it.id, it]));
    const pageHeight = doc.internal.pageSize.getHeight();
    for (const [itemId, narrative] of Object.entries(input.narratives)) {
      const item = itemsById.get(itemId);
      if (!item) continue;
      const heading = `${item.control?.controlCode ?? '—'} · ${item.control?.name ?? ''}`;
      const headingLines = doc.splitTextToSize(heading, 540 - margin * 2);
      const bodyLines = doc.splitTextToSize(narrative, 540 - margin * 2);
      const blockHeight = headingLines.length * 14 + bodyLines.length * 12 + 20;

      if (nY + blockHeight > pageHeight - 56) {
        doc.addPage();
        nY = margin;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(20);
      doc.text(headingLines, margin, nY);
      nY += headingLines.length * 14 + 4;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(60);
      doc.text(bodyLines, margin, nY);
      nY += bodyLines.length * 12 + 14;
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Aegis Compliance Evidence · run ${run.id} · page ${p} of ${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 24
    );
  }

  return doc.output('blob');
}

function buildManifest(input: PackageInput): string {
  const { run, framework, items, tenantName } = input;
  return JSON.stringify(
    {
      schemaVersion: 1,
      generatedAt: new Date().toISOString(),
      framework: {
        code: framework.code,
        name: framework.name,
        version: framework.version,
      },
      tenant: { name: tenantName },
      run: {
        id: run.id,
        startedAt: run.startedAt.toISOString(),
        completedAt: run.completedAt?.toISOString() ?? null,
        status: run.status,
        totalControls: run.totalControls,
        counts: {
          passed: run.passedCount,
          failed: run.failedCount,
          na: run.naCount,
          error: run.errorCount,
        },
      },
      controls: items.map((it) => ({
        controlCode: it.control?.controlCode,
        name: it.control?.name,
        severity: it.control?.severity,
        status: it.status,
        notes: it.notes,
        evaluatedAt: it.evaluatedAt.toISOString(),
        snapshotFile: `controls/${safeFileName(it.control?.controlCode ?? it.id)}.json`,
      })),
    },
    null,
    2
  );
}

export async function downloadEvidencePackage(input: PackageInput): Promise<void> {
  const zip = new JSZip();

  const coverBlob = buildCoverPdf(input);
  const coverBuf = await coverBlob.arrayBuffer();
  zip.file('cover.pdf', coverBuf);

  zip.file('manifest.json', buildManifest(input));

  // AI narratives as a separate markdown file for non-PDF consumers (issue #4).
  if (input.narratives && Object.keys(input.narratives).length > 0) {
    const itemsById = new Map(input.items.map((it) => [it.id, it]));
    const sections: string[] = ['# AI-generated narratives', ''];
    sections.push(
      `Generated for run ${input.run.id}. Verify before relying on for audit response.`,
      ''
    );
    for (const [itemId, narrative] of Object.entries(input.narratives)) {
      const item = itemsById.get(itemId);
      if (!item) continue;
      sections.push(
        `## ${item.control?.controlCode ?? '—'} · ${item.control?.name ?? ''}`,
        '',
        `**Status:** ${item.status.toUpperCase()}${item.control?.severity ? ` · **Severity:** ${item.control.severity}` : ''}`,
        '',
        narrative,
        ''
      );
    }
    zip.file('narratives.md', sections.join('\n'));
  }

  const controls = zip.folder('controls');
  for (const it of input.items) {
    const code = safeFileName(it.control?.controlCode ?? it.id);
    controls?.file(
      `${code}.json`,
      JSON.stringify(
        {
          controlCode: it.control?.controlCode,
          name: it.control?.name,
          severity: it.control?.severity,
          status: it.status,
          notes: it.notes,
          evaluatedAt: it.evaluatedAt.toISOString(),
          snapshot: it.snapshot,
        },
        null,
        2
      )
    );
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  const ts = (input.run.completedAt ?? input.run.startedAt)
    .toISOString()
    .replace(/[:.]/g, '-')
    .slice(0, 19);
  const baseName = safeFileName(`${input.framework.code}_${input.tenantName}_${ts}`);
  saveAs(blob, `${baseName}.zip`);
}
