// Report Template Registry - 100+ out-of-the-box report templates

export type ReportCategory = 
  | 'security'
  | 'compliance'
  | 'identity'
  | 'devices'
  | 'exchange'
  | 'sharepoint'
  | 'teams'
  | 'licensing'
  | 'copilot'
  | 'drift'
  | 'tenant_health'
  | 'billing';

export interface ReportTemplate {
  id: string;
  name: string;
  category: ReportCategory;
  description: string;
  dataSources: string[];
  metrics: string[];
  filters: string[];
  estimatedTime: string; // e.g., "< 1 min", "1-2 min"
}

export const REPORT_CATEGORIES: { id: ReportCategory; name: string; icon: string; description: string }[] = [
  { id: 'security', name: 'Security', icon: 'Shield', description: 'Security posture and threat analysis' },
  { id: 'compliance', name: 'Compliance', icon: 'CheckCircle', description: 'Regulatory and policy compliance' },
  { id: 'identity', name: 'Identity & Access', icon: 'Users', description: 'User accounts and access management' },
  { id: 'devices', name: 'Devices & Intune', icon: 'Laptop', description: 'Device compliance and management' },
  { id: 'exchange', name: 'Exchange', icon: 'Mail', description: 'Email and mail flow analytics' },
  { id: 'sharepoint', name: 'SharePoint & OneDrive', icon: 'HardDrive', description: 'Document and sharing analytics' },
  { id: 'teams', name: 'Teams', icon: 'MessageSquare', description: 'Teams usage and collaboration' },
  { id: 'licensing', name: 'Licensing', icon: 'CreditCard', description: 'License usage and optimization' },
  { id: 'copilot', name: 'Copilot', icon: 'Sparkles', description: 'Microsoft Copilot adoption and usage' },
  { id: 'drift', name: 'Drift & Changes', icon: 'GitCompare', description: 'Configuration drift and change tracking' },
  { id: 'tenant_health', name: 'Tenant Health', icon: 'Activity', description: 'Tenant health and service status' },
  { id: 'billing', name: 'Billing & Usage', icon: 'BarChart3', description: 'Cost and resource utilization' },
];

export const REPORT_TEMPLATES: ReportTemplate[] = [
  // ============ SECURITY REPORTS (15+) ============
  {
    id: 'sec-conditional-access-summary',
    name: 'Conditional Access Summary',
    category: 'security',
    description: 'Overview of all Conditional Access policies, their status, and coverage gaps',
    dataSources: ['conditionalAccessPolicies', 'users', 'groups'],
    metrics: ['totalPolicies', 'enabledPolicies', 'userCoverage', 'grantControls'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'sec-mfa-gaps',
    name: 'MFA Coverage Gaps',
    category: 'security',
    description: 'Identify users and scenarios without Multi-Factor Authentication protection',
    dataSources: ['users', 'authenticationMethods', 'conditionalAccessPolicies'],
    metrics: ['mfaEnabledUsers', 'mfaGaps', 'gapsByDepartment', 'riskLevel'],
    filters: ['customer', 'tenant', 'userType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'sec-risky-users',
    name: 'Risky Users Report',
    category: 'security',
    description: 'Users flagged for risky behavior or compromised credentials',
    dataSources: ['riskyUsers', 'signInLogs', 'users'],
    metrics: ['riskLevel', 'riskState', 'lastRiskyActivity', 'userDetails'],
    filters: ['customer', 'tenant', 'riskLevel', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'sec-risky-signins',
    name: 'Risky Sign-Ins Analysis',
    category: 'security',
    description: 'Analysis of suspicious and risky sign-in attempts',
    dataSources: ['riskySignIns', 'signInLogs', 'users'],
    metrics: ['totalRiskySignIns', 'byRiskLevel', 'byLocation', 'byApp'],
    filters: ['customer', 'tenant', 'riskLevel', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'sec-admin-accounts',
    name: 'Admin Accounts Audit',
    category: 'security',
    description: 'Comprehensive audit of privileged admin accounts and their security posture',
    dataSources: ['directoryRoles', 'users', 'authenticationMethods'],
    metrics: ['totalAdmins', 'mfaStatus', 'lastSignIn', 'roleAssignments'],
    filters: ['customer', 'tenant', 'roleType'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'sec-external-sharing-audit',
    name: 'External Sharing Audit',
    category: 'security',
    description: 'Audit of files and folders shared externally from SharePoint and OneDrive',
    dataSources: ['sharingLinks', 'driveItems', 'users'],
    metrics: ['externalShares', 'anonymousLinks', 'byUser', 'bySite'],
    filters: ['customer', 'tenant', 'dateRange', 'sharingType'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'sec-security-alerts',
    name: 'Security Alerts Summary',
    category: 'security',
    description: 'Overview of active security alerts from Microsoft Defender',
    dataSources: ['securityAlerts', 'incidents'],
    metrics: ['totalAlerts', 'bySeverity', 'byCategory', 'resolvedVsActive'],
    filters: ['customer', 'tenant', 'severity', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'sec-secure-score-breakdown',
    name: 'Secure Score Breakdown',
    category: 'security',
    description: 'Detailed breakdown of Microsoft Secure Score by category',
    dataSources: ['secureScore', 'secureScoreControlProfiles'],
    metrics: ['currentScore', 'maxScore', 'byCategory', 'improvementActions'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'sec-app-consent-grants',
    name: 'App Consent Grants',
    category: 'security',
    description: 'Review of OAuth app consent grants and permissions',
    dataSources: ['oauth2PermissionGrants', 'servicePrincipals', 'users'],
    metrics: ['totalGrants', 'byApp', 'byPermission', 'riskLevel'],
    filters: ['customer', 'tenant', 'permissionType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'sec-password-policy-compliance',
    name: 'Password Policy Compliance',
    category: 'security',
    description: 'Analysis of password policy settings and compliance across tenants',
    dataSources: ['authorizationPolicy', 'users', 'domains'],
    metrics: ['policySettings', 'complianceRate', 'expiringPasswords'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'sec-blocked-users',
    name: 'Blocked Users Report',
    category: 'security',
    description: 'List of users with blocked sign-in status',
    dataSources: ['users'],
    metrics: ['totalBlocked', 'blockReason', 'lastActivity', 'accountAge'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'sec-pim-assignments',
    name: 'PIM Role Assignments',
    category: 'security',
    description: 'Privileged Identity Management role assignments and eligibility',
    dataSources: ['roleAssignments', 'roleEligibilitySchedules', 'users'],
    metrics: ['activeAssignments', 'eligibleAssignments', 'byRole', 'pendingApprovals'],
    filters: ['customer', 'tenant', 'roleType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'sec-named-locations',
    name: 'Named Locations Audit',
    category: 'security',
    description: 'Review of named locations used in Conditional Access policies',
    dataSources: ['namedLocations', 'conditionalAccessPolicies'],
    metrics: ['totalLocations', 'byType', 'policyUsage', 'trustedLocations'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'sec-authentication-methods',
    name: 'Authentication Methods Report',
    category: 'security',
    description: 'Overview of authentication methods registered by users',
    dataSources: ['authenticationMethods', 'users'],
    metrics: ['byMethodType', 'userCoverage', 'passwordlessAdoption', 'fido2Keys'],
    filters: ['customer', 'tenant', 'methodType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'sec-legacy-auth',
    name: 'Legacy Authentication Usage',
    category: 'security',
    description: 'Identify usage of legacy authentication protocols',
    dataSources: ['signInLogs', 'conditionalAccessPolicies'],
    metrics: ['legacyAuthAttempts', 'byProtocol', 'byUser', 'byApp'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '2-3 min',
  },

  // ============ COMPLIANCE REPORTS (20+) ============
  {
    id: 'comp-iso27001-summary',
    name: 'ISO 27001 Compliance Summary',
    category: 'compliance',
    description: 'Compliance status against ISO 27001 security controls',
    dataSources: ['complianceResults', 'conditionalAccessPolicies', 'deviceCompliance'],
    metrics: ['overallScore', 'controlsPassed', 'controlsFailed', 'gapsByDomain'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-soc2-summary',
    name: 'SOC 2 Compliance Summary',
    category: 'compliance',
    description: 'Compliance status against SOC 2 Trust Service Criteria',
    dataSources: ['complianceResults', 'auditLogs', 'accessReviews'],
    metrics: ['overallScore', 'byPrinciple', 'criticalGaps', 'recommendations'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-hipaa-summary',
    name: 'HIPAA Compliance Summary',
    category: 'compliance',
    description: 'Compliance status against HIPAA security and privacy requirements',
    dataSources: ['complianceResults', 'dlpPolicies', 'sensitivityLabels'],
    metrics: ['overallScore', 'securityRuleCompliance', 'privacyRuleCompliance', 'gaps'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-gdpr-summary',
    name: 'GDPR Compliance Summary',
    category: 'compliance',
    description: 'Compliance status against GDPR data protection requirements',
    dataSources: ['complianceResults', 'dlpPolicies', 'retentionPolicies', 'dataSubjectRequests'],
    metrics: ['overallScore', 'dataInventory', 'consentManagement', 'dsrHandling'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-nist-summary',
    name: 'NIST Framework Summary',
    category: 'compliance',
    description: 'Compliance status against NIST Cybersecurity Framework',
    dataSources: ['complianceResults', 'securityPolicies'],
    metrics: ['overallScore', 'byFunction', 'maturityLevel', 'recommendations'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-cis-benchmark',
    name: 'CIS Benchmark Report',
    category: 'compliance',
    description: 'Compliance against CIS Microsoft 365 Foundations Benchmark',
    dataSources: ['complianceResults', 'organizationSettings'],
    metrics: ['overallScore', 'level1Compliance', 'level2Compliance', 'recommendations'],
    filters: ['customer', 'tenant', 'cisLevel'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-pci-dss-summary',
    name: 'PCI DSS Compliance Summary',
    category: 'compliance',
    description: 'Compliance status against PCI DSS requirements',
    dataSources: ['complianceResults', 'encryptionSettings', 'accessControls'],
    metrics: ['overallScore', 'byRequirement', 'criticalGaps', 'recommendations'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-fedramp-summary',
    name: 'FedRAMP Compliance Summary',
    category: 'compliance',
    description: 'Compliance status against FedRAMP requirements',
    dataSources: ['complianceResults', 'securityPolicies'],
    metrics: ['overallScore', 'byControlFamily', 'gaps', 'impactLevel'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-trend-analysis',
    name: 'Compliance Trend Analysis',
    category: 'compliance',
    description: 'Historical trend of compliance scores over time',
    dataSources: ['complianceHistory'],
    metrics: ['scoreOverTime', 'improvementRate', 'regressions', 'predictions'],
    filters: ['customer', 'tenant', 'baseline', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'comp-failed-checks',
    name: 'Failed Compliance Checks',
    category: 'compliance',
    description: 'Detailed list of all failed compliance checks with remediation guidance',
    dataSources: ['complianceResults'],
    metrics: ['failedChecks', 'bySeverity', 'byCategory', 'remediation'],
    filters: ['customer', 'tenant', 'baseline', 'severity'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'comp-dlp-policy-report',
    name: 'DLP Policy Report',
    category: 'compliance',
    description: 'Data Loss Prevention policy configuration and matches',
    dataSources: ['dlpPolicies', 'dlpMatches'],
    metrics: ['totalPolicies', 'matchesByPolicy', 'byLocation', 'falsePositiveRate'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-sensitivity-labels',
    name: 'Sensitivity Labels Report',
    category: 'compliance',
    description: 'Usage and adoption of sensitivity labels across the tenant',
    dataSources: ['sensitivityLabels', 'labeledContent'],
    metrics: ['labelAdoption', 'byLabel', 'byContentType', 'unlabeledContent'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-retention-policies',
    name: 'Retention Policies Report',
    category: 'compliance',
    description: 'Overview of retention policies and their application',
    dataSources: ['retentionPolicies', 'retentionLabels'],
    metrics: ['totalPolicies', 'byLocation', 'retentionPeriods', 'compliance'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'comp-audit-log-analysis',
    name: 'Audit Log Analysis',
    category: 'compliance',
    description: 'Analysis of audit log activities for compliance monitoring',
    dataSources: ['auditLogs'],
    metrics: ['activityVolume', 'byOperation', 'byUser', 'anomalies'],
    filters: ['customer', 'tenant', 'activityType', 'dateRange'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'comp-edr-compliance',
    name: 'EDR Compliance Report',
    category: 'compliance',
    description: 'Endpoint Detection and Response compliance status',
    dataSources: ['deviceCompliance', 'defenderStatus'],
    metrics: ['coverage', 'healthyEndpoints', 'missingAgents', 'outdatedSignatures'],
    filters: ['customer', 'tenant', 'deviceType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-executive-summary',
    name: 'Executive Compliance Summary',
    category: 'compliance',
    description: 'High-level compliance summary for executive stakeholders',
    dataSources: ['complianceResults', 'complianceHistory'],
    metrics: ['overallPosture', 'keyRisks', 'improvements', 'priorities'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'comp-multi-tenant-comparison',
    name: 'Multi-Tenant Compliance Comparison',
    category: 'compliance',
    description: 'Compare compliance scores across multiple tenants',
    dataSources: ['complianceResults', 'tenantConnections'],
    metrics: ['scoreByTenant', 'commonGaps', 'bestPractices', 'outliers'],
    filters: ['customer', 'baseline'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-access-reviews',
    name: 'Access Reviews Report',
    category: 'compliance',
    description: 'Summary of access review campaigns and decisions',
    dataSources: ['accessReviews', 'accessReviewDecisions'],
    metrics: ['totalReviews', 'completionRate', 'decisions', 'pendingReviews'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'comp-terms-of-use',
    name: 'Terms of Use Compliance',
    category: 'compliance',
    description: 'User acceptance status for terms of use agreements',
    dataSources: ['termsOfUse', 'termsOfUseAcceptances'],
    metrics: ['totalTerms', 'acceptanceRate', 'pendingAcceptances', 'expiringTerms'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'comp-information-barriers',
    name: 'Information Barriers Report',
    category: 'compliance',
    description: 'Configuration and effectiveness of information barriers',
    dataSources: ['informationBarriers', 'informationBarrierSegments'],
    metrics: ['totalPolicies', 'segmentCoverage', 'violations', 'compliance'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },

  // ============ IDENTITY & ACCESS REPORTS (15+) ============
  {
    id: 'ident-privileged-users',
    name: 'Privileged Users Report',
    category: 'identity',
    description: 'Comprehensive list of users with privileged roles',
    dataSources: ['directoryRoles', 'roleAssignments', 'users'],
    metrics: ['totalPrivileged', 'byRole', 'mfaStatus', 'lastSignIn'],
    filters: ['customer', 'tenant', 'roleType'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'ident-group-membership',
    name: 'Group Membership Analysis',
    category: 'identity',
    description: 'Analysis of group memberships and nesting',
    dataSources: ['groups', 'groupMembers'],
    metrics: ['totalGroups', 'averageMembers', 'nestedGroups', 'dynamicGroups'],
    filters: ['customer', 'tenant', 'groupType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'ident-guest-users',
    name: 'Guest Users Report',
    category: 'identity',
    description: 'Audit of external guest users in the tenant',
    dataSources: ['users', 'signInLogs'],
    metrics: ['totalGuests', 'byDomain', 'activeGuests', 'staleGuests'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'ident-stale-accounts',
    name: 'Stale Accounts Report',
    category: 'identity',
    description: 'Users who haven\'t signed in within specified period',
    dataSources: ['users', 'signInLogs'],
    metrics: ['staleAccounts', 'byPeriod', 'licensedStale', 'adminStale'],
    filters: ['customer', 'tenant', 'stalePeriod'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'ident-app-registrations',
    name: 'App Registrations Report',
    category: 'identity',
    description: 'Overview of application registrations and their secrets',
    dataSources: ['applications', 'servicePrincipals'],
    metrics: ['totalApps', 'expiringSecrets', 'highPrivilegeApps', 'multiTenantApps'],
    filters: ['customer', 'tenant', 'appType'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'ident-service-principals',
    name: 'Service Principals Audit',
    category: 'identity',
    description: 'Audit of service principals and their permissions',
    dataSources: ['servicePrincipals', 'appRoleAssignments'],
    metrics: ['totalPrincipals', 'byType', 'permissions', 'riskLevel'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'ident-user-licenses',
    name: 'User License Assignments',
    category: 'identity',
    description: 'Detailed view of license assignments per user',
    dataSources: ['users', 'licensedProducts'],
    metrics: ['usersByLicense', 'multiLicensedUsers', 'unlicensedUsers'],
    filters: ['customer', 'tenant', 'licenseType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'ident-sign-in-activity',
    name: 'Sign-In Activity Report',
    category: 'identity',
    description: 'User sign-in activity and patterns',
    dataSources: ['signInLogs', 'users'],
    metrics: ['signInsByUser', 'byLocation', 'byDevice', 'failures'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'ident-directory-sync',
    name: 'Directory Sync Status',
    category: 'identity',
    description: 'Status of directory synchronization from on-premises',
    dataSources: ['organization', 'domains', 'users'],
    metrics: ['syncStatus', 'syncErrors', 'syncedObjects', 'lastSync'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'ident-admin-units',
    name: 'Administrative Units Report',
    category: 'identity',
    description: 'Overview of administrative units and their members',
    dataSources: ['administrativeUnits', 'adminUnitMembers'],
    metrics: ['totalUnits', 'membersByUnit', 'scopedRoles', 'coverage'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'ident-b2b-collaboration',
    name: 'B2B Collaboration Report',
    category: 'identity',
    description: 'Analysis of B2B collaboration settings and usage',
    dataSources: ['crossTenantAccessPolicy', 'users'],
    metrics: ['partnerOrgs', 'invitedUsers', 'collaborationSettings', 'restrictions'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'ident-deleted-users',
    name: 'Deleted Users Report',
    category: 'identity',
    description: 'List of recently deleted users with recovery options',
    dataSources: ['deletedUsers'],
    metrics: ['totalDeleted', 'recoverableUsers', 'permanentlyDeleted', 'deletionReason'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'ident-user-settings',
    name: 'User Settings Audit',
    category: 'identity',
    description: 'Audit of user-configurable settings and preferences',
    dataSources: ['users', 'mailboxSettings'],
    metrics: ['byLanguage', 'byTimezone', 'delegatedAccess', 'forwardingRules'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'ident-password-expiry',
    name: 'Password Expiry Report',
    category: 'identity',
    description: 'Users with passwords expiring soon',
    dataSources: ['users', 'authorizationPolicy'],
    metrics: ['expiringPasswords', 'expiredPasswords', 'neverExpires', 'byPeriod'],
    filters: ['customer', 'tenant', 'expiryPeriod'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'ident-emergency-access',
    name: 'Emergency Access Accounts',
    category: 'identity',
    description: 'Status and configuration of emergency access accounts',
    dataSources: ['users', 'directoryRoles', 'signInLogs'],
    metrics: ['emergencyAccounts', 'lastUsed', 'mfaStatus', 'recommendations'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },

  // ============ DEVICES & INTUNE REPORTS (15+) ============
  {
    id: 'dev-compliance-overview',
    name: 'Device Compliance Overview',
    category: 'devices',
    description: 'Overall device compliance status across the tenant',
    dataSources: ['managedDevices', 'deviceCompliancePolicies'],
    metrics: ['compliantDevices', 'nonCompliantDevices', 'byPlatform', 'byPolicy'],
    filters: ['customer', 'tenant', 'platform', 'complianceStatus'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-autopilot-status',
    name: 'Autopilot Deployment Status',
    category: 'devices',
    description: 'Status of Windows Autopilot deployments',
    dataSources: ['autopilotDevices', 'autopilotProfiles'],
    metrics: ['totalDevices', 'deploymentStatus', 'profileAssignments', 'failures'],
    filters: ['customer', 'tenant', 'deploymentStatus'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-app-deployment',
    name: 'App Deployment Status',
    category: 'devices',
    description: 'Status of application deployments to devices',
    dataSources: ['mobileApps', 'appInstallStatus'],
    metrics: ['totalApps', 'installSuccess', 'installFailures', 'pendingInstalls'],
    filters: ['customer', 'tenant', 'appType', 'platform'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-update-rings',
    name: 'Update Ring Status',
    category: 'devices',
    description: 'Windows Update ring configurations and compliance',
    dataSources: ['windowsUpdateForBusinessPolicies', 'updateStatus'],
    metrics: ['ringConfigurations', 'updateCompliance', 'pendingUpdates', 'failures'],
    filters: ['customer', 'tenant', 'ringName'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-script-failures',
    name: 'Device Script Failures',
    category: 'devices',
    description: 'PowerShell and shell script execution failures on devices',
    dataSources: ['deviceManagementScripts', 'scriptRunStatus'],
    metrics: ['totalScripts', 'successRate', 'failedDevices', 'errorDetails'],
    filters: ['customer', 'tenant', 'scriptName'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-configuration-profiles',
    name: 'Configuration Profile Status',
    category: 'devices',
    description: 'Status of device configuration profile deployments',
    dataSources: ['deviceConfigurations', 'configurationStatus'],
    metrics: ['totalProfiles', 'successRate', 'conflicts', 'errors'],
    filters: ['customer', 'tenant', 'platform', 'profileType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-encryption-status',
    name: 'Device Encryption Status',
    category: 'devices',
    description: 'BitLocker and FileVault encryption status across devices',
    dataSources: ['managedDevices', 'encryptionStatus'],
    metrics: ['encryptedDevices', 'unencryptedDevices', 'encryptionErrors', 'keyEscrow'],
    filters: ['customer', 'tenant', 'platform'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-os-versions',
    name: 'OS Version Distribution',
    category: 'devices',
    description: 'Distribution of operating system versions across devices',
    dataSources: ['managedDevices'],
    metrics: ['byOSVersion', 'outdatedDevices', 'supportedVersions', 'upgradeRecommendations'],
    filters: ['customer', 'tenant', 'platform'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'dev-defender-status',
    name: 'Defender Status Report',
    category: 'devices',
    description: 'Microsoft Defender for Endpoint status on managed devices',
    dataSources: ['managedDevices', 'defenderStatus'],
    metrics: ['protectedDevices', 'signatureStatus', 'scanStatus', 'threats'],
    filters: ['customer', 'tenant', 'protectionStatus'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-corporate-owned',
    name: 'Corporate Owned Devices',
    category: 'devices',
    description: 'Inventory of corporate-owned devices',
    dataSources: ['managedDevices'],
    metrics: ['totalCorporate', 'byPlatform', 'enrollmentDate', 'primaryUser'],
    filters: ['customer', 'tenant', 'platform', 'enrollmentType'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'dev-byod-devices',
    name: 'BYOD Devices Report',
    category: 'devices',
    description: 'Personal devices enrolled in the tenant',
    dataSources: ['managedDevices'],
    metrics: ['totalBYOD', 'byPlatform', 'appProtectionStatus', 'compliance'],
    filters: ['customer', 'tenant', 'platform'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'dev-enrollment-failures',
    name: 'Enrollment Failures Report',
    category: 'devices',
    description: 'Failed device enrollment attempts and causes',
    dataSources: ['enrollmentStatus', 'troubleshootingEvents'],
    metrics: ['failedEnrollments', 'byError', 'byPlatform', 'recommendations'],
    filters: ['customer', 'tenant', 'platform', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-app-protection',
    name: 'App Protection Status',
    category: 'devices',
    description: 'Mobile Application Management (MAM) policy status',
    dataSources: ['appProtectionPolicies', 'managedAppStatuses'],
    metrics: ['protectedApps', 'policyCompliance', 'wiped Apps', 'jailbrokenDevices'],
    filters: ['customer', 'tenant', 'platform'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-hardware-inventory',
    name: 'Hardware Inventory Report',
    category: 'devices',
    description: 'Hardware specifications of managed devices',
    dataSources: ['managedDevices'],
    metrics: ['byManufacturer', 'byModel', 'storageCapacity', 'memorySize'],
    filters: ['customer', 'tenant', 'platform', 'manufacturer'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'dev-stale-devices',
    name: 'Stale Devices Report',
    category: 'devices',
    description: 'Devices that haven\'t checked in recently',
    dataSources: ['managedDevices'],
    metrics: ['staleDevices', 'lastCheckIn', 'byPlatform', 'recommendations'],
    filters: ['customer', 'tenant', 'stalePeriod'],
    estimatedTime: '< 1 min',
  },

  // ============ EXCHANGE REPORTS (10+) ============
  {
    id: 'exch-mail-flow',
    name: 'Mail Flow Summary',
    category: 'exchange',
    description: 'Overview of email traffic and delivery statistics',
    dataSources: ['mailFlowStats', 'messageTrace'],
    metrics: ['sentMessages', 'receivedMessages', 'blockedMessages', 'deliveryRate'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'exch-transport-rules',
    name: 'Transport Rules Audit',
    category: 'exchange',
    description: 'Audit of mail flow transport rules and their impact',
    dataSources: ['transportRules'],
    metrics: ['totalRules', 'enabledRules', 'ruleMatches', 'impactedMessages'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'exch-mailbox-permissions',
    name: 'Mailbox Permissions Report',
    category: 'exchange',
    description: 'Delegated access and permissions on mailboxes',
    dataSources: ['mailboxPermissions', 'mailboxes'],
    metrics: ['delegatedMailboxes', 'byPermissionType', 'fullAccessGrants', 'sendAsGrants'],
    filters: ['customer', 'tenant', 'permissionType'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'exch-mobile-devices',
    name: 'Exchange Mobile Devices',
    category: 'exchange',
    description: 'Mobile devices connected via Exchange ActiveSync',
    dataSources: ['mobileDevices'],
    metrics: ['totalDevices', 'byDeviceType', 'allowedDevices', 'quarantinedDevices'],
    filters: ['customer', 'tenant', 'deviceStatus'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'exch-mailbox-sizes',
    name: 'Mailbox Size Report',
    category: 'exchange',
    description: 'Mailbox storage usage and quota status',
    dataSources: ['mailboxStats'],
    metrics: ['totalStorage', 'averageSize', 'overQuotaMailboxes', 'largestMailboxes'],
    filters: ['customer', 'tenant', 'quotaStatus'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'exch-shared-mailboxes',
    name: 'Shared Mailboxes Report',
    category: 'exchange',
    description: 'Inventory and usage of shared mailboxes',
    dataSources: ['sharedMailboxes', 'mailboxPermissions'],
    metrics: ['totalShared', 'memberCount', 'lastActivity', 'storageUsed'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'exch-connectors',
    name: 'Mail Connectors Report',
    category: 'exchange',
    description: 'Inbound and outbound mail connector configurations',
    dataSources: ['inboundConnectors', 'outboundConnectors'],
    metrics: ['totalConnectors', 'byType', 'tlsSettings', 'partnerOrgs'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'exch-spam-filtering',
    name: 'Spam Filtering Report',
    category: 'exchange',
    description: 'Spam and malware filtering statistics',
    dataSources: ['spamFilterPolicy', 'threatProtectionStatus'],
    metrics: ['spamBlocked', 'malwareBlocked', 'phishingBlocked', 'falsePositives'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'exch-forwarding-rules',
    name: 'Email Forwarding Rules',
    category: 'exchange',
    description: 'Audit of automatic email forwarding rules',
    dataSources: ['inboxRules', 'mailboxSettings'],
    metrics: ['forwardingEnabled', 'externalForwarding', 'byDestination', 'riskLevel'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'exch-public-folders',
    name: 'Public Folders Report',
    category: 'exchange',
    description: 'Public folder hierarchy and usage statistics',
    dataSources: ['publicFolders', 'publicFolderStats'],
    metrics: ['totalFolders', 'storageUsed', 'itemCount', 'lastAccess'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },

  // ============ SHAREPOINT & ONEDRIVE REPORTS (8+) ============
  {
    id: 'sp-sharing-report',
    name: 'External Sharing Report',
    category: 'sharepoint',
    description: 'Files and sites shared with external users',
    dataSources: ['sharingLinks', 'siteSharing'],
    metrics: ['externalShares', 'anonymousLinks', 'byUser', 'bySite'],
    filters: ['customer', 'tenant', 'sharingType', 'dateRange'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'sp-storage-usage',
    name: 'Storage Usage Report',
    category: 'sharepoint',
    description: 'SharePoint and OneDrive storage consumption',
    dataSources: ['sites', 'drives'],
    metrics: ['totalStorage', 'bySite', 'byUser', 'growthTrend'],
    filters: ['customer', 'tenant', 'siteType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'sp-external-sites',
    name: 'External User Site Access',
    category: 'sharepoint',
    description: 'Sites accessible to external users',
    dataSources: ['sites', 'sitePermissions'],
    metrics: ['sitesWithExternal', 'externalUserCount', 'permissionTypes', 'riskLevel'],
    filters: ['customer', 'tenant'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'sp-anonymous-links',
    name: 'Anonymous Links Report',
    category: 'sharepoint',
    description: 'Files shared via anonymous (anyone) links',
    dataSources: ['sharingLinks'],
    metrics: ['totalAnonymous', 'byFile', 'expirationStatus', 'accessCount'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'sp-site-permissions',
    name: 'Site Permissions Audit',
    category: 'sharepoint',
    description: 'Detailed permissions audit for SharePoint sites',
    dataSources: ['sites', 'sitePermissions', 'siteGroups'],
    metrics: ['uniquePermissions', 'inheritedPermissions', 'directGrants', 'groupMemberships'],
    filters: ['customer', 'tenant', 'siteUrl'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'sp-inactive-sites',
    name: 'Inactive Sites Report',
    category: 'sharepoint',
    description: 'SharePoint sites with no recent activity',
    dataSources: ['sites', 'siteActivity'],
    metrics: ['inactiveSites', 'lastActivity', 'storageUsed', 'ownerInfo'],
    filters: ['customer', 'tenant', 'inactivePeriod'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'sp-onedrive-usage',
    name: 'OneDrive Usage Report',
    category: 'sharepoint',
    description: 'OneDrive storage usage by user',
    dataSources: ['drives', 'users'],
    metrics: ['totalStorage', 'byUser', 'quotaStatus', 'syncStatus'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'sp-sensitivity-labels',
    name: 'Site Sensitivity Labels',
    category: 'sharepoint',
    description: 'Sensitivity label application on SharePoint sites',
    dataSources: ['sites', 'sensitivityLabels'],
    metrics: ['labeledSites', 'byLabel', 'unlabeledSites', 'compliance'],
    filters: ['customer', 'tenant', 'label'],
    estimatedTime: '1-2 min',
  },

  // ============ TEAMS REPORTS (8+) ============
  {
    id: 'teams-usage',
    name: 'Teams Usage Report',
    category: 'teams',
    description: 'Overall Teams adoption and usage statistics',
    dataSources: ['teamsActivity', 'users'],
    metrics: ['activeUsers', 'messageCount', 'meetingCount', 'callCount'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'teams-guest-access',
    name: 'Teams Guest Access Report',
    category: 'teams',
    description: 'Guest user access to Teams and channels',
    dataSources: ['teams', 'teamMembers'],
    metrics: ['teamsWithGuests', 'guestCount', 'byTeam', 'accessLevel'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'teams-app-usage',
    name: 'Teams App Usage',
    category: 'teams',
    description: 'Third-party and custom app usage in Teams',
    dataSources: ['teamsApps', 'appUsage'],
    metrics: ['installedApps', 'byApp', 'userAdoption', 'permissionGrants'],
    filters: ['customer', 'tenant', 'appType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'teams-meeting-policies',
    name: 'Meeting Policies Report',
    category: 'teams',
    description: 'Teams meeting policy configurations and assignments',
    dataSources: ['meetingPolicies', 'policyAssignments'],
    metrics: ['totalPolicies', 'byPolicy', 'userAssignments', 'settings'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'teams-inactive-teams',
    name: 'Inactive Teams Report',
    category: 'teams',
    description: 'Teams with no recent activity',
    dataSources: ['teams', 'teamActivity'],
    metrics: ['inactiveTeams', 'lastActivity', 'memberCount', 'ownerInfo'],
    filters: ['customer', 'tenant', 'inactivePeriod'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'teams-private-channels',
    name: 'Private Channels Report',
    category: 'teams',
    description: 'Private channels across Teams',
    dataSources: ['teams', 'channels'],
    metrics: ['totalPrivate', 'byTeam', 'memberCount', 'sharedChannels'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'teams-external-access',
    name: 'External Access Settings',
    category: 'teams',
    description: 'Teams external and federation access configurations',
    dataSources: ['externalAccessSettings', 'federationSettings'],
    metrics: ['federatedDomains', 'blockedDomains', 'skypeInterop', 'teamsOnlyMode'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'teams-phone-system',
    name: 'Teams Phone System Report',
    category: 'teams',
    description: 'Teams calling and phone system usage',
    dataSources: ['callingPolicies', 'phoneNumbers', 'callRecords'],
    metrics: ['phoneUsers', 'callVolume', 'numberInventory', 'voicemailUsage'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },

  // ============ LICENSING REPORTS (12+) ============
  {
    id: 'lic-utilization',
    name: 'License Utilization Report',
    category: 'licensing',
    description: 'Overall license utilization across SKUs',
    dataSources: ['subscribedSkus', 'users'],
    metrics: ['totalLicenses', 'assignedLicenses', 'availableLicenses', 'utilizationRate'],
    filters: ['customer', 'tenant', 'skuType'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'lic-unused-licenses',
    name: 'Unused Licenses Report',
    category: 'licensing',
    description: 'Licenses assigned to inactive or stale users',
    dataSources: ['users', 'signInLogs', 'subscribedSkus'],
    metrics: ['unusedLicenses', 'byLicenseType', 'potentialSavings', 'recommendations'],
    filters: ['customer', 'tenant', 'stalePeriod'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'lic-sku-distribution',
    name: 'SKU Distribution Report',
    category: 'licensing',
    description: 'Distribution of license SKUs across users',
    dataSources: ['subscribedSkus', 'users'],
    metrics: ['bySku', 'userCount', 'servicePlans', 'expirationDates'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'lic-user-matrix',
    name: 'User-License Matrix',
    category: 'licensing',
    description: 'Matrix view of users and their license assignments',
    dataSources: ['users', 'subscribedSkus'],
    metrics: ['userLicenseMapping', 'multiLicensedUsers', 'conflictingAssignments'],
    filters: ['customer', 'tenant', 'department'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'lic-cost-analysis',
    name: 'License Cost Analysis',
    category: 'licensing',
    description: 'Cost breakdown and analysis of license spend',
    dataSources: ['subscribedSkus', 'billingUsage'],
    metrics: ['totalCost', 'bySku', 'costPerUser', 'savingsOpportunities'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'lic-expiring-subscriptions',
    name: 'Expiring Subscriptions',
    category: 'licensing',
    description: 'Subscriptions expiring within specified period',
    dataSources: ['subscribedSkus'],
    metrics: ['expiringSubscriptions', 'byDate', 'affectedUsers', 'renewalRecommendations'],
    filters: ['customer', 'tenant', 'expiryPeriod'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'lic-service-plans',
    name: 'Service Plans Report',
    category: 'licensing',
    description: 'Individual service plan enablement status',
    dataSources: ['subscribedSkus', 'users'],
    metrics: ['enabledPlans', 'disabledPlans', 'byUser', 'recommendations'],
    filters: ['customer', 'tenant', 'servicePlan'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'lic-group-assignments',
    name: 'Group-Based License Assignments',
    category: 'licensing',
    description: 'License assignments through Azure AD groups',
    dataSources: ['groups', 'groupLicenseAssignments'],
    metrics: ['groupsWithLicenses', 'memberCount', 'processingState', 'errors'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'lic-trial-subscriptions',
    name: 'Trial Subscriptions Report',
    category: 'licensing',
    description: 'Active trial subscriptions and expiration dates',
    dataSources: ['subscribedSkus'],
    metrics: ['activeTrials', 'expirationDates', 'conversionRecommendations'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'lic-duplicate-licenses',
    name: 'Duplicate Licenses Report',
    category: 'licensing',
    description: 'Users with overlapping or duplicate license features',
    dataSources: ['users', 'subscribedSkus'],
    metrics: ['duplicateAssignments', 'overlappingFeatures', 'potentialSavings'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'lic-optimization',
    name: 'License Optimization Report',
    category: 'licensing',
    description: 'AI-powered recommendations for license optimization',
    dataSources: ['users', 'subscribedSkus', 'signInLogs', 'usageReports'],
    metrics: ['optimizationScore', 'recommendations', 'potentialSavings', 'actionItems'],
    filters: ['customer', 'tenant'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'lic-historical-changes',
    name: 'License Change History',
    category: 'licensing',
    description: 'Historical changes to license assignments',
    dataSources: ['auditLogs'],
    metrics: ['assignmentChanges', 'byUser', 'byAdmin', 'changeVolume'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },

  // ============ COPILOT REPORTS (5+) ============
  {
    id: 'copilot-adoption',
    name: 'Copilot Adoption Report',
    category: 'copilot',
    description: 'Microsoft Copilot license adoption and enablement',
    dataSources: ['copilotLicenses', 'users'],
    metrics: ['licensedUsers', 'activeUsers', 'adoptionRate', 'byDepartment'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'copilot-usage',
    name: 'Copilot Usage Report',
    category: 'copilot',
    description: 'Copilot usage patterns and feature adoption',
    dataSources: ['copilotUsage'],
    metrics: ['totalInteractions', 'byFeature', 'byApp', 'userEngagement'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'copilot-readiness',
    name: 'Copilot Readiness Assessment',
    category: 'copilot',
    description: 'Tenant readiness for Copilot deployment',
    dataSources: ['copilotReadiness', 'dataGovernance'],
    metrics: ['readinessScore', 'prerequisites', 'dataQuality', 'recommendations'],
    filters: ['customer', 'tenant'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'copilot-roi',
    name: 'Copilot ROI Analysis',
    category: 'copilot',
    description: 'Return on investment analysis for Copilot deployment',
    dataSources: ['copilotUsage', 'productivityMetrics'],
    metrics: ['timeSaved', 'productivityGain', 'costPerUser', 'roi'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'copilot-plugins',
    name: 'Copilot Plugins Report',
    category: 'copilot',
    description: 'Custom and third-party Copilot plugin usage',
    dataSources: ['copilotPlugins', 'pluginUsage'],
    metrics: ['installedPlugins', 'usageByPlugin', 'userAdoption', 'permissions'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },

  // ============ DRIFT & CHANGES REPORTS (8+) ============
  {
    id: 'drift-weekly-summary',
    name: 'Weekly Drift Summary',
    category: 'drift',
    description: 'Summary of configuration drift detected in the past week',
    dataSources: ['scheduledDriftRuns', 'driftResults'],
    metrics: ['totalDrift', 'byResourceType', 'severity', 'resolution'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'drift-change-timeline',
    name: 'Change Timeline Report',
    category: 'drift',
    description: 'Chronological view of detected configuration changes',
    dataSources: ['driftResults', 'auditLogs'],
    metrics: ['changes', 'byDate', 'byResource', 'byUser'],
    filters: ['customer', 'tenant', 'dateRange', 'resourceType'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'drift-policy-changes',
    name: 'Policy Changes Report',
    category: 'drift',
    description: 'Changes to policies (CA, compliance, etc.)',
    dataSources: ['driftResults', 'policySnapshots'],
    metrics: ['policyChanges', 'byPolicyType', 'beforeAfter', 'impact'],
    filters: ['customer', 'tenant', 'policyType', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'drift-unauthorized-changes',
    name: 'Unauthorized Changes Report',
    category: 'drift',
    description: 'Changes made outside of approved change windows',
    dataSources: ['driftResults', 'changeWindows', 'auditLogs'],
    metrics: ['unauthorizedChanges', 'byAdmin', 'byResource', 'severity'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'drift-rollback-history',
    name: 'Rollback History Report',
    category: 'drift',
    description: 'History of configuration rollbacks performed',
    dataSources: ['rollbackHistory'],
    metrics: ['totalRollbacks', 'byResource', 'success', 'failures'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'drift-comparison',
    name: 'Tenant Comparison Report',
    category: 'drift',
    description: 'Compare configurations between tenants or baselines',
    dataSources: ['tenantConfigurations', 'baselines'],
    metrics: ['differences', 'byCategory', 'alignmentScore', 'recommendations'],
    filters: ['customer', 'sourceTenant', 'targetTenant'],
    estimatedTime: '2-3 min',
  },
  {
    id: 'drift-baseline-deviation',
    name: 'Baseline Deviation Report',
    category: 'drift',
    description: 'Deviations from established configuration baselines',
    dataSources: ['baselines', 'currentConfigurations'],
    metrics: ['deviations', 'bySeverity', 'byCategory', 'remediation'],
    filters: ['customer', 'tenant', 'baseline'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'drift-trend-analysis',
    name: 'Drift Trend Analysis',
    category: 'drift',
    description: 'Historical trend of drift detection over time',
    dataSources: ['scheduledDriftRuns'],
    metrics: ['driftOverTime', 'peakPeriods', 'resolution Time', 'patterns'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },

  // ============ TENANT HEALTH REPORTS (8+) ============
  {
    id: 'health-score-trend',
    name: 'Health Score Trend',
    category: 'tenant_health',
    description: 'Historical trend of tenant health scores',
    dataSources: ['tenantHealthChecks'],
    metrics: ['scoreOverTime', 'improvements', 'degradations', 'predictions'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'health-service-status',
    name: 'Service Health Report',
    category: 'tenant_health',
    description: 'Microsoft 365 service health and incidents',
    dataSources: ['serviceHealth', 'incidents'],
    metrics: ['activeIncidents', 'resolvedIncidents', 'affectedServices', 'uptime'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'health-sync-status',
    name: 'Directory Sync Health',
    category: 'tenant_health',
    description: 'Health of directory synchronization',
    dataSources: ['syncStatus', 'syncErrors'],
    metrics: ['syncHealth', 'lastSync', 'errors', 'objectCounts'],
    filters: ['customer', 'tenant'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'health-api-errors',
    name: 'API Error Report',
    category: 'tenant_health',
    description: 'Graph API and integration errors',
    dataSources: ['apiLogs', 'errorLogs'],
    metrics: ['errorRate', 'byEndpoint', 'byErrorType', 'trends'],
    filters: ['customer', 'tenant', 'dateRange'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'health-token-expiry',
    name: 'Token Expiry Report',
    category: 'tenant_health',
    description: 'Service principal and app token expiration status',
    dataSources: ['servicePrincipals', 'applications'],
    metrics: ['expiringTokens', 'expiredTokens', 'byApp', 'urgency'],
    filters: ['customer', 'tenant', 'expiryPeriod'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'health-multi-tenant',
    name: 'Multi-Tenant Health Overview',
    category: 'tenant_health',
    description: 'Aggregate health status across all managed tenants',
    dataSources: ['tenantConnections', 'tenantHealthChecks'],
    metrics: ['healthyTenants', 'warningTenants', 'criticalTenants', 'trends'],
    filters: ['customer'],
    estimatedTime: '1-2 min',
  },
  {
    id: 'health-connection-status',
    name: 'Connection Status Report',
    category: 'tenant_health',
    description: 'Status of tenant connections and authentication',
    dataSources: ['tenantConnections', 'authStatus'],
    metrics: ['connectedTenants', 'disconnected', 'authErrors', 'lastCheck'],
    filters: ['customer'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'health-resource-quotas',
    name: 'Resource Quotas Report',
    category: 'tenant_health',
    description: 'Tenant resource quotas and utilization',
    dataSources: ['tenantQuotas', 'resourceUsage'],
    metrics: ['quotaUtilization', 'nearLimitResources', 'trends', 'recommendations'],
    filters: ['customer', 'tenant'],
    estimatedTime: '1-2 min',
  },

  // ============ BILLING & USAGE REPORTS (Additional) ============
  {
    id: 'bill-resource-usage',
    name: 'Resource Usage Report',
    category: 'billing',
    description: 'Detailed resource usage for billing purposes',
    dataSources: ['billingUsage', 'exportJobs'],
    metrics: ['totalResources', 'byType', 'byCustomer', 'trend'],
    filters: ['customer', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'bill-customer-summary',
    name: 'Customer Billing Summary',
    category: 'billing',
    description: 'Per-customer billing summary and breakdown',
    dataSources: ['billingUsage', 'customers'],
    metrics: ['billableAmount', 'resourceBreakdown', 'userCount', 'trend'],
    filters: ['customer', 'dateRange'],
    estimatedTime: '< 1 min',
  },
  {
    id: 'bill-export-history',
    name: 'Export History Report',
    category: 'billing',
    description: 'History of exports performed for billing tracking',
    dataSources: ['exportJobs'],
    metrics: ['totalExports', 'byCustomer', 'byFormat', 'success Rate'],
    filters: ['customer', 'dateRange'],
    estimatedTime: '< 1 min',
  },
];

// Helper functions
export function getTemplatesByCategory(category: ReportCategory): ReportTemplate[] {
  return REPORT_TEMPLATES.filter(t => t.category === category);
}

export function getTemplateById(id: string): ReportTemplate | undefined {
  return REPORT_TEMPLATES.find(t => t.id === id);
}

export function searchTemplates(query: string): ReportTemplate[] {
  const lowerQuery = query.toLowerCase();
  return REPORT_TEMPLATES.filter(t => 
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery) ||
    t.category.toLowerCase().includes(lowerQuery)
  );
}

export function getTemplateCount(): number {
  return REPORT_TEMPLATES.length;
}

export function getCategoryStats(): { category: ReportCategory; count: number }[] {
  const stats = new Map<ReportCategory, number>();
  for (const template of REPORT_TEMPLATES) {
    stats.set(template.category, (stats.get(template.category) || 0) + 1);
  }
  return Array.from(stats.entries()).map(([category, count]) => ({ category, count }));
}
