project_id = "rcvtxvpyqmfuunnpsqny"

[functions.graph-api]
verify_jwt = false

[functions.azure-api]
verify_jwt = false

[functions.convert-format]
verify_jwt = false

[functions.run-scheduled-export]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false

[functions.run-scheduled-drift]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.create-psa-ticket]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.collect-usage]
verify_jwt = false

[functions.deploy-policy]
verify_jwt = false

[functions.run-scheduled-deployment]
verify_jwt = false
