import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ConvertRequest {
  data: any;
  resourceType: string;
  format: 'terraform' | 'bicep' | 'powershell';
}

async function verifyAuth(req: Request): Promise<{ userId: string } | { error: string; status: number }> {
  const authHeader = req.headers.get('Authorization');
  
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return { error: 'Missing or invalid authorization header', status: 401 };
  }

  const token = authHeader.replace('Bearer ', '');
  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const supabaseKey = Deno.env.get('SUPABASE_ANON_KEY')!;
  
  const supabase = createClient(supabaseUrl, supabaseKey, {
    global: {
      headers: { Authorization: authHeader },
    },
  });

  const { data, error } = await supabase.auth.getClaims(token);
  
  if (error || !data?.claims) {
    console.error('Auth verification failed:', error);
    return { error: 'Unauthorized', status: 401 };
  }

  return { userId: data.claims.sub as string };
}

// Convert JSON to Terraform HCL
function toTerraform(data: any, resourceType: string): string {
  const resources: string[] = [];
  const items = Array.isArray(data) ? data : [data];

  for (const item of items) {
    const resourceName = (item.displayName || item.name || item.id || 'resource')
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');

    let terraformResource = '';

    switch (resourceType) {
      case 'conditional-access/ca-policies':
        terraformResource = generateCATerraform(item, resourceName);
        break;
      case 'entra-id/groups':
        terraformResource = generateGroupTerraform(item, resourceName);
        break;
      case 'intune/device-configurations':
        terraformResource = generateDeviceConfigTerraform(item, resourceName);
        break;
      case 'intune/compliance-policies':
        terraformResource = generateComplianceTerraform(item, resourceName);
        break;
      default:
        // Generic conversion
        terraformResource = generateGenericTerraform(item, resourceName, resourceType);
    }

    resources.push(terraformResource);
  }

  const header = `# Generated by M365 Export Tool
# Resource Type: ${resourceType}
# Generated: ${new Date().toISOString()}

terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

`;

  return header + resources.join('\n\n');
}

function generateCATerraform(policy: any, name: string): string {
  return `resource "azuread_conditional_access_policy" "${name}" {
  display_name = "${policy.displayName || ''}"
  state        = "${policy.state || 'disabled'}"

  conditions {
    client_app_types = ${JSON.stringify(policy.conditions?.clientAppTypes || [])}

    applications {
      included_applications = ${JSON.stringify(policy.conditions?.applications?.includeApplications || ['All'])}
      excluded_applications = ${JSON.stringify(policy.conditions?.applications?.excludeApplications || [])}
    }

    users {
      included_users  = ${JSON.stringify(policy.conditions?.users?.includeUsers || [])}
      excluded_users  = ${JSON.stringify(policy.conditions?.users?.excludeUsers || [])}
      included_groups = ${JSON.stringify(policy.conditions?.users?.includeGroups || [])}
      excluded_groups = ${JSON.stringify(policy.conditions?.users?.excludeGroups || [])}
    }

    ${policy.conditions?.locations ? `locations {
      included_locations = ${JSON.stringify(policy.conditions.locations.includeLocations || [])}
      excluded_locations = ${JSON.stringify(policy.conditions.locations.excludeLocations || [])}
    }` : ''}
  }

  grant_controls {
    operator          = "${policy.grantControls?.operator || 'OR'}"
    built_in_controls = ${JSON.stringify(policy.grantControls?.builtInControls || [])}
  }
}`;
}

function generateGroupTerraform(group: any, name: string): string {
  const isUnified = group.groupTypes?.includes('Unified');
  const isDynamic = group.membershipRule ? true : false;

  return `resource "azuread_group" "${name}" {
  display_name     = "${group.displayName || ''}"
  description      = "${(group.description || '').replace(/"/g, '\\"')}"
  security_enabled = ${group.securityEnabled || false}
  mail_enabled     = ${group.mailEnabled || false}
  mail_nickname    = "${group.mailNickname || name}"
  ${isUnified ? 'types = ["Unified"]' : ''}
  ${isDynamic ? `
  dynamic_membership {
    enabled = true
    rule    = "${(group.membershipRule || '').replace(/"/g, '\\"')}"
  }` : ''}
}`;
}

function generateDeviceConfigTerraform(config: any, name: string): string {
  return `# Device Configuration Profile: ${config.displayName}
# Note: Full Intune device configuration requires the Microsoft Graph Provider
# This is a reference configuration

resource "azurerm_intune_device_configuration" "${name}" {
  display_name = "${config.displayName || ''}"
  description  = "${(config.description || '').replace(/"/g, '\\"')}"
  
  # Platform-specific settings would go here
  # Export the JSON below and use with Intune Graph API or PowerShell

  # Original settings (as comment):
  # ${JSON.stringify(config, null, 2).split('\n').join('\n  # ')}
}`;
}

function generateComplianceTerraform(policy: any, name: string): string {
  return `# Compliance Policy: ${policy.displayName}
# Note: Intune compliance policies require Microsoft Graph provider

resource "azurerm_intune_device_compliance_policy" "${name}" {
  display_name = "${policy.displayName || ''}"
  description  = "${(policy.description || '').replace(/"/g, '\\"')}"

  # Platform-specific compliance settings
  # Reference the exported JSON for full configuration
}`;
}

function generateGenericTerraform(item: any, name: string, resourceType: string): string {
  return `# Resource: ${item.displayName || item.name || name}
# Type: ${resourceType}
# ID: ${item.id || 'N/A'}

# This resource requires manual Terraform configuration
# Exported data:
/*
${JSON.stringify(item, null, 2)}
*/`;
}

// Convert JSON to Bicep
function toBicep(data: any, resourceType: string): string {
  const items = Array.isArray(data) ? data : [data];
  const resources: string[] = [];

  const header = `// Generated by M365 Export Tool
// Resource Type: ${resourceType}
// Generated: ${new Date().toISOString()}

targetScope = 'subscription'

`;

  for (const item of items) {
    const resourceName = (item.displayName || item.name || item.id || 'resource')
      .replace(/[^a-zA-Z0-9]/g, '_');

    switch (resourceType) {
      case 'entra-id/groups':
        resources.push(generateGroupBicep(item, resourceName));
        break;
      default:
        resources.push(generateGenericBicep(item, resourceName, resourceType));
    }
  }

  return header + resources.join('\n\n');
}

function generateGroupBicep(group: any, name: string): string {
  return `// Group: ${group.displayName}
// Note: Azure AD groups in Bicep require Microsoft.Graph resource provider

resource group_${name} 'Microsoft.Graph/groups@v1.0' = {
  displayName: '${group.displayName || ''}'
  description: '${(group.description || '').replace(/'/g, "\\'")}'
  mailEnabled: ${group.mailEnabled || false}
  mailNickname: '${group.mailNickname || name}'
  securityEnabled: ${group.securityEnabled || false}
}`;
}

function generateGenericBicep(item: any, name: string, resourceType: string): string {
  return `// Resource: ${item.displayName || item.name || name}
// Type: ${resourceType}
// This resource may require Microsoft.Graph or custom deployment

/*
Exported configuration:
${JSON.stringify(item, null, 2)}
*/`;
}

// Convert JSON to PowerShell
function toPowerShell(data: any, resourceType: string): string {
  const items = Array.isArray(data) ? data : [data];
  const scripts: string[] = [];

  const header = `# Generated by M365 Export Tool
# Resource Type: ${resourceType}
# Generated: ${new Date().toISOString()}

# Requires: Microsoft.Graph PowerShell SDK
# Install-Module Microsoft.Graph -Scope CurrentUser

# Connect to Microsoft Graph
# Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All", "Policy.ReadWrite.ConditionalAccess", "Group.ReadWrite.All"

`;

  for (const item of items) {
    switch (resourceType) {
      case 'conditional-access/ca-policies':
        scripts.push(generateCAPowerShell(item));
        break;
      case 'entra-id/groups':
        scripts.push(generateGroupPowerShell(item));
        break;
      case 'intune/device-configurations':
        scripts.push(generateDeviceConfigPowerShell(item));
        break;
      case 'intune/compliance-policies':
        scripts.push(generateCompliancePowerShell(item));
        break;
      default:
        scripts.push(generateGenericPowerShell(item, resourceType));
    }
  }

  return header + scripts.join('\n\n');
}

function generateCAPowerShell(policy: any): string {
  return `# Conditional Access Policy: ${policy.displayName}
$policyParams = @{
    DisplayName = "${policy.displayName || ''}"
    State = "${policy.state || 'disabled'}"
    Conditions = @{
        ClientAppTypes = @(${(policy.conditions?.clientAppTypes || []).map((t: string) => `"${t}"`).join(', ')})
        Applications = @{
            IncludeApplications = @(${(policy.conditions?.applications?.includeApplications || []).map((a: string) => `"${a}"`).join(', ')})
        }
        Users = @{
            IncludeUsers = @(${(policy.conditions?.users?.includeUsers || []).map((u: string) => `"${u}"`).join(', ')})
        }
    }
    GrantControls = @{
        Operator = "${policy.grantControls?.operator || 'OR'}"
        BuiltInControls = @(${(policy.grantControls?.builtInControls || []).map((c: string) => `"${c}"`).join(', ')})
    }
}

New-MgIdentityConditionalAccessPolicy -BodyParameter $policyParams`;
}

function generateGroupPowerShell(group: any): string {
  return `# Group: ${group.displayName}
$groupParams = @{
    DisplayName = "${group.displayName || ''}"
    Description = "${(group.description || '').replace(/"/g, '\\"')}"
    MailEnabled = $${group.mailEnabled || false}
    MailNickname = "${group.mailNickname || 'group'}"
    SecurityEnabled = $${group.securityEnabled || false}
    ${group.groupTypes?.includes('Unified') ? 'GroupTypes = @("Unified")' : ''}
}

New-MgGroup -BodyParameter $groupParams`;
}

function generateDeviceConfigPowerShell(config: any): string {
  return `# Device Configuration: ${config.displayName}
# Note: Device configurations require specific Graph API calls based on platform

$configBody = @'
${JSON.stringify(config, null, 2)}
'@

# Create the device configuration
$uri = "https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations"
Invoke-MgGraphRequest -Method POST -Uri $uri -Body $configBody -ContentType "application/json"`;
}

function generateCompliancePowerShell(policy: any): string {
  return `# Compliance Policy: ${policy.displayName}
$policyBody = @'
${JSON.stringify(policy, null, 2)}
'@

# Create the compliance policy
$uri = "https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicies"
Invoke-MgGraphRequest -Method POST -Uri $uri -Body $policyBody -ContentType "application/json"`;
}

function generateGenericPowerShell(item: any, resourceType: string): string {
  return `# Resource: ${item.displayName || item.name || 'Unknown'}
# Type: ${resourceType}

# Generic export - review and modify as needed
$resourceBody = @'
${JSON.stringify(item, null, 2)}
'@

# TODO: Add appropriate Graph API call for this resource type
Write-Host "Resource exported: ${item.displayName || item.name || item.id}"`;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Verify authentication first
    const authResult = await verifyAuth(req);
    if ('error' in authResult) {
      console.log('Authentication failed:', authResult.error);
      return new Response(
        JSON.stringify({ error: authResult.error }),
        { status: authResult.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('Authenticated user:', authResult.userId);

    const body: ConvertRequest = await req.json();
    const { data, resourceType, format } = body;

    if (!data || !resourceType || !format) {
      return new Response(
        JSON.stringify({ error: 'Missing required parameters: data, resourceType, format' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    let result: string;

    switch (format) {
      case 'terraform':
        result = toTerraform(data, resourceType);
        break;
      case 'bicep':
        result = toBicep(data, resourceType);
        break;
      case 'powershell':
        result = toPowerShell(data, resourceType);
        break;
      default:
        return new Response(
          JSON.stringify({ error: `Unsupported format: ${format}` }),
          { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        output: result,
        format,
        resourceType,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: unknown) {
    console.error('Convert error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Conversion failed';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});